export default class Country{
  
  countries:Array<string> = ["Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua/Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Saba",
  "Bosnia-Herz.",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "Brit.Ind.Oc.Ter",
  "Brit.Virgin Is.",
  "Brunei Daruss.",
  "Bulgaria",
  "Burkina Faso",
  "Burma",
  "Burundi",
  "CAR",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Canary Islands",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Christmas Islnd",
  "Coconut Islands",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Dem. Rep. Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Rep.",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guin",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islnds",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "Frenc.Polynesia",
  "French Guayana",
  "French S.Territ",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard/McDon.Isl",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islnds",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Minor Outl.Isl.",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "N.Mariana Islnd",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Norway",
  "Obsolete",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Pap. New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islnds",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Rep.of Congo",
  "Reunion",
  "Romania",
  "Rwanda",
  "S. Sandwich Ins",
  "S.Tome,Principe",
  "Saint Helena",
  "Samoa",
  "Samoa, America",
  "San Marino",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Serbia/Monten.",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "St Kitts&amp;Nevis",
  "St. Lucia",
  "St. Martin",
  "St. Vincent",
  "St.Pier,Miquel.",
  "Sudan",
  "Suriname",
  "Svalbard",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau Islands",
  "Tonga",
  "Treasury Synth",
  "Trinidad,Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turksh Caicosin",
  "Tuvalu",
  "U.S. Virgin Is.",
  "USA",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "Uruguay",
  "Utd.Arab Emir.",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wallis,Futuna",
  "West Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"]

}

